In [1]:
import numpy as np
import time

### Data Creation Routines 
generally have a first parameter which is the shape of the object, can be a single value or a tuple

Examples below

In [ ]:
# Numpy routines which allocate memory and fill arrays with value

a = np.zeros(4); # np.zeros() create a vector of zeros specified length in parameter in bracket. in this case a = [0, 0, 0, 0], shape (4,) where shape(row, col)
a = np.zeros((4,)); # more explicit version, where you specify the column length too
np.random.random_sample(4); # gives you a random number generation of 4 random row values between 0 & 1

# Numpy routines which allocate memory and fill arrays with value BUT DO NOT ACCEPT SHAPE AS INPUT ARGUEMENT
a = np.arange(4.);
a = np.random.rand(4);


### Key differences between the two above
1. when shape is specified, array is initiated with a specified shape, and values are filled from the specified shape
2. when shape is not specified, array shape of vector is implied based on the number of valeus created. 

In [14]:
# Most basic way of creating Numpy arrays
a = np.array([5,3,43,2]) # values are just specified
a = np.array([1], [2], [3]) # creates a 2 dimentional array(matrix) with 3 rows, 1 column 
a = np.array([[1, 2], [2, 2], [3, 2]]) # creates a 2dim array with 3 rows, 2 columns, first column containing 1,2,3 and 2nd col containing 2,2,2

[ 5  3 43  2]


: 

### Creating in Numpy Arrays
1. 1 dimentional array -> (4,) or (4), creates a 1 dimentional array with 4 values
2. 2 dimentional array -> (4,0), creates a 2 dimentional array with 4 rows, 0 columns, ***(rows, columns)
3. adding dimentions -> (4,0,0) # 3 dimentions, (4,0,0,0) # 4 dimentions etc

**(,4) -> invalid

### Indexing Numpy Arrays

Indexing -> reffring to a value(s) in an array by its position within the array

Slicing -> getting a subset of elements from an array based on their indicies

In [10]:
# Indexing
a = np.arange(10)
print(a)
# Accessing an Element
a[0] # returns the 1st element
a[1] # returns the 2nd element
a[-1] # returns the last element
a[-2] # returns the 2nd last element

# Slicing, syntax is vector[start:stop:step]
# important to note, starting value is inclusive, stopping value is exclusive, stepping values 
a[2:7:2] # start in the 3rd position (since 0 is the 1st position), and do not return values that are beyond 6th position(6th position exclusive), and have a distance of 3 indexes 
# above will return [2, 4, 6]
a[3:] # access all elements 3 and above 3rd inclusive 
a[:3] # access all elements 3 and below 3rd exclusive
a[:] # access all elements 

[0 1 2 3 4 5 6 7 8 9]


array([2, 4, 6])

In [11]:
# Useful Single Vector Operations
a = np.array([1,2,3,4])
b = -a # [-1, -2, -3, -4]
b = a**2 # [1, 4, 9, 16]
b = np.sum(a) #10
b = np.mean(a) #2.5


In [12]:
# dot product or sum product
c = np.dot(a,b)